wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1671340726.477251
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.13.5
      8:
      - 5
aug_p:
  desc: null
  value: 0.5
bs:
  desc: null
  value: 384
cj_a:
  desc: null
  value: 1.5
cj_b:
  desc: null
  value: 20
dataset:
  desc: null
  value: cifar100
drop:
  desc: null
  value: 0.2
epoch:
  desc: null
  value: 500
gs_f:
  desc: null
  value: 3
gs_s:
  desc: null
  value: 1.0
head_size:
  desc: null
  value: 4096
lr:
  desc: null
  value: 0.001
opt:
  desc: null
  value: adam
ro_a:
  desc: null
  value: 15
wandb:
  desc: null
  value: my-experiment
